### ISSUE TITLE
Testing Markdown language

### ISSUE THREAD

**Issue by JeanPedroso** [JeanPedroso/Hello-Word#1]
I will be testing markdown language here.

**Comment by JeanPedroso** [comment]
# Title
---
_I_ ~~am~~ learning **Markdown** language in the __*Git*__ and Github Video Course.
***
## Numbered list:
1. test
1. test 2
   1. With three spaces creates a sub item.
   1. sub
## Demarcade list:
* test
* test
   * test
## Task list:
- [x] Create home page.
- [ ] Create the store page.
- [ ] End the meeting with the client.
- [ ] Receive payment.
#### **ADDING IMAGE** : *dragging the image here in the text.*
![grasshopper](https://user-images.githubusercontent.com/62728026/79167636-4dc16680-7dbe-11ea-813e-09269acf0fc9.jpg)
[Access my GitHub](https://JeanPedroso.github.io)

**Comment by JeanPedroso** [comment]
# Table:
Num | Name | Note
---|---|---
1 | *Jean* | **10**
2 | *Ana* | **10**

**Comment by JeanPedroso** [comment]
## Betwenn backs is a command. 
`jean.txt`

**Comment by JeanPedroso** [comment]
#### Writing in programming code:
```
name = input ( 'Type your name: ')
print ('Nice to meet', name)
```
